### ISSUE TITLE
The audio does not play when you click start audio

### ISSUE THREAD

**Issue by pjsg** [fventuri/ka9q-web#3]
I can see the waterfall and I can pan and zoom around in it. When I clicked 'start audio' I expected to hear something. 

I put some breakpoints in the webapp, and I'm never getting the 0x7A message from the websocket (which would send the audio data into the audiocontext). I'm wondering if this is ka9q-web problem or I don't have my ka9q-radio configuration appropriately set.

**Comment by fventuri** [comment]
@pjsg - I think Phil Karn KA9Q  made a few changes to 'ka9q-radio' recently, which might affect those 0x7A messages.

I would instrument the program 'radiod' by adding some print statements to log when those 0x7A messages are sent;. After that, it should be relatively easy to figure out why 'ka9q-web' doesn't see them.

Franco

**Comment by pjsg** [comment]
One of the issues is that in ka9q-web, it never gets to the call to decode_radio_status -- this is because the tag never matches. It isn't (currently) clear why.

With some more debugging, it *appears* that the control_poll from ka9q-web is never received by ka9q-radio. At least that is what appears to be happening (or, rather, not happening). IN particular it appears that decode_radio_commands is not called with the message that is sent from ka9q-web.

I'm running on an x86-64 box. If this works for you, what platform are you running on?

**Comment by fventuri** [comment]
@pjsg - My PC is an x86-64 running Fedora Core 39, but the last time I ran ka9q-web was a couple of months (or perhaps three) ago, and I know Phil Karn has been making many changes to ka9q-radio that likely broke ka9q-web.

I would suggest that you posted a message describing your problem to the ka9q-radio mailing list in Google groups (https://groups.google.com/g/ka9q-radio): there are many users of ka9q-radio in that group (including Phil), and several of them run ka9q-web too, so they might be able to help you with this problem (and perhaps suggest modifications for ka9q-web to make it work again).

Franco

**Comment by pjsg** [comment]
This problem seems solved in commit e7252b1.
